from faker import Faker
from datetime import datetime, timedelta
import random
from pathlib import Path

TOTAL_COUNT = 100_000
BATCH_SIZE = 1_000

OUTPUT_PATH = Path("db/init/02-seed.sql")

fake = Faker("ko_KR")

CATEGORIES = {
    "스키": [
        "비발디파크 리프트권",
        "하이원 스키장 리프트권",
        "용평리조트 스키 패스",
        "곤지암리조트 야간권",
        "무주 덕유산 리프트권",
    ],
    "워터파크": [
        "오션월드 종일권",
        "캐리비안베이 오후권",
        "롯데워터파크 입장권",
        "설악 워터피아 이용권",
        "아산 스파비스 이용권",
    ],
    "숙박": [
        "강릉 오션뷰 숙박권",
        "부산 해운대 호텔 숙박권",
        "제주 리조트 1박 이용권",
        "가평 풀빌라 숙박권",
        "속초 리조트 숙박권",
    ],
}

STATUSES = ["CONFIRMED", "CANCELLED", "PENDING"]


def escape_sql(value: str) -> str:
    return value.replace("'", "''")


def random_order_date() -> str:
    base = datetime.now()
    random_date = base - timedelta(
        days=random.randint(0, 365),
        hours=random.randint(0, 23),
        minutes=random.randint(0, 59),
        seconds=random.randint(0, 59),
    )
    return random_date.strftime("%Y-%m-%d %H:%M:%S")


def generate_row() -> str:
    category = random.choice(list(CATEGORIES.keys()))
    product_name = random.choice(CATEGORIES[category])

    user_name = fake.name()
    amount = random.randint(10_000, 300_000)
    status = random.choice(STATUSES)
    order_date = random_order_date()

    return (
        f"('{escape_sql(user_name)}', "
        f"'{escape_sql(product_name)}', "
        f"'{escape_sql(category)}', "
        f"{amount}, "
        f"'{escape_sql(status)}', "
        f"'{order_date}')"
    )


def main():
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    with OUTPUT_PATH.open("w", encoding="utf-8") as file:
        file.write("-- Auto-generated seed data for PlayStory assignment\n")
        file.write("-- Generated by scripts/generate_seed_sql.py\n\n")

        for start in range(1, TOTAL_COUNT + 1, BATCH_SIZE):
            end = min(start + BATCH_SIZE - 1, TOTAL_COUNT)

            file.write(
                "INSERT INTO orders "
                "(user_name, product_name, category, amount, status, order_date) VALUES\n"
            )

            rows = [generate_row() for _ in range(start, end + 1)]
            file.write(",\n".join(rows))
            file.write(";\n\n")

    print(f"Generated {TOTAL_COUNT:,} rows into {OUTPUT_PATH}")


if __name__ == "__main__":
    main()